swiftnav_ros2_driver:
  ros__parameters:

    # SwiftNav GNSS Receiver Interface
    interface: 1 # 1: TCP Client, 2: Serial, 3: File

    # TCP Client (interface: 1)
    host_ip: "192.168.1.101"
    host_port: 55555
    read_timeout: 2000  # [ms]
    write_timeout: 2000 # [ms]

    # ROS2 Frame Name
    frame_name: "swiftnav-gnss-rover"

    # Topic Publication Time Stamp Source
    timestamp_source_gnss: False # True: use GNSS receiver reported time (default), False: use current platfrom time

    # RTK Baseline Direction Offsets (Baseline Topic)
    baseline_dir_offset_deg: 0.0    # [deg], range [-180 to 180]
    baseline_dip_offset_deg: 0.0    # [deg], range [-90 to 90]

    # Mininal Speed For Track Updates From SBP Message VEL NED COV (GPSFix Topic)
    track_update_min_speed_mps: 0.1 # [m/s], Track and track error outputs are 'frozen' below this threshold.

    # Publishers
    enabled_publishers:
      [
        "gpsfix",
        "navsatfix",
        "twistwithcovariancestamped",
        "baseline",
        "timereference",
        "imu"
      ]

    # SBP Logging
    log_sbp_messages: False
    log_sbp_filepath: "/home/swiftnav/ros2logs"

